FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5000
EXPOSE 5001

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["MotorcycleRental/MotorcycleRental.Api/MotorcycleRental.Api.csproj", "MotorcycleRental/MotorcycleRental.Api/"]
COPY ["MotorcycleRental/MotorcycleRental.Application/MotorcycleRental.Application.csproj", "MotorcycleRental/MotorcycleRental.Application/"]
COPY ["MotorcycleRental/MotorcycleRental.Domain/MotorcycleRental.Domain.csproj", "MotorcycleRental/MotorcycleRental.Domain/"]
COPY ["MotorcycleRental/MotorcycleRental.Infrastructure/MotorcycleRental.Infrastructure.csproj", "MotorcycleRental/MotorcycleRental.Infrastructure/"]

RUN dotnet restore "MotorcycleRental/MotorcycleRental.Api/MotorcycleRental.Api.csproj"

COPY . .
WORKDIR "/src/MotorcycleRental/MotorcycleRental.Api"
RUN dotnet build "MotorcycleRental.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MotorcycleRental.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MotorcycleRental.Api.dll"]
