# 1. Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copia apenas os projetos necessários para restore
COPY ["MotorcycleRental/MotorcycleRental.Consumer/MotorcycleRental.Consumer.csproj", "MotorcycleRental.Consumer/"]
COPY ["MotorcycleRental/MotorcycleRental.Application/MotorcycleRental.Application.csproj", "MotorcycleRental.Application/"]
COPY ["MotorcycleRental/MotorcycleRental.Domain/MotorcycleRental.Domain.csproj", "MotorcycleRental.Domain/"]
COPY ["MotorcycleRental/MotorcycleRental.Infrastructure/MotorcycleRental.Infrastructure.csproj", "MotorcycleRental.Infrastructure/"]

# Restaura pacotes
RUN dotnet restore "MotorcycleRental.Consumer/MotorcycleRental.Consumer.csproj"

# Copia todo o código
COPY . .

WORKDIR "/src/MotorcycleRental/MotorcycleRental.Consumer"

# Build e publish
RUN dotnet build "MotorcycleRental.Consumer.csproj" -c Release -o /app/build
RUN dotnet publish "MotorcycleRental.Consumer.csproj" -c Release -o /app/publish

# 2. Stage final
FROM mcr.microsoft.com/dotnet/runtime:8.0 AS final
WORKDIR /app

# Aqui o Docker copia do stage correto chamado "publish"
COPY --from=build /app/publish .

# Variável para detectar container
ENV DOTNET_RUNNING_IN_CONTAINER=true

# Entrypoint
ENTRYPOINT ["dotnet", "MotorcycleRental.Consumer.dll"]
